<Project>
  <PropertyGroup>
    <ModVersion>0.1.0</ModVersion>
    <ModGuid>com.lennoxp90.factoryclassic</ModGuid>
    <ModName>FactoryClassic</ModName>
    <PluginFolder>LennoxP90-FactoryClassic</PluginFolder>
    <SptRoot Condition="'$(SptRoot)' == ''">C:\SPT C\SPT-4.1-Clean</SptRoot>
    <SptManaged>$(SptRoot)\EscapeFromTarkov_Data\Managed</SptManaged>
    <SptBepInEx>$(SptRoot)\BepInEx</SptBepInEx>
    <Configuration Condition="'$(Configuration)' == ''">Debug</Configuration>
    <DistRoot>$(MSBuildThisFileDirectory)dist\$(Configuration)\</DistRoot>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
